### ISSUE TITLE
Add a configuration system

### ISSUE THREAD

**Issue by nevinera** [nevinera/quiet_quality#13]
Allow a configuration object that can load from a yaml file - I'm picturing a format like:

```yaml
---
annotators: [github_stdout]
executor: parallel
tools:
  standardrb:
    all_files: true
    filter_messages: false
  rubocop:
    all_files: false
    filter_messages: true
```

(So we can later specify more config per tool).

When running the script we can (a) specify the path to a config file on the command line,  or (b) look for a `.quiet_quality.yml` file in the current directory if the path wasn't supplied on the CLI.

The goal is to make it so that, in a project, you can specify the config in a config file, and then just call `qq` without any arguments, and it'll only run the appropriate tools, with the configured options.

Note - the options supplied on the CLI (described in #34) affect all tools, and override these settings, but running `bin/qq` with no options at all, should run exactly the set of tools specified in the config file, and each tool should be configured individually based on the per-tool settings there. If you run the script specifying a _tool_, and the tool is present in the configuration file, that tool should use the configuration file's settings (unless overridden).
