### ISSUE TITLE
support eslint

### ISSUE THREAD

**Issue by nevinera** [nevinera/quiet_quality#50]
The most popular linting framework for frontend code - seems valuable to support :-)

**Comment by nevinera** [comment]
I poked at this one a bit already @JonathanWThom, but the problem I ran into is that the way you _run_ eslint isn't consistent. Most projects seem to specify a bunch of the config for the tool by creating one or more package.json script entries that runs eslint with additional arguments supplied, and they name them just whatever they feel like.

I think we might need to hold off on this until we have a way to let users supply their own `command` (and/or base_command`) for certain tools through the config file, like

```
eslint:
  base_command: ".node_modules/bin/eslint --foo --bar --config .myconfig.json"
  filter_messages: true
  changed_files: true
```

I ticketed that as its own issue [here](https://github.com/nevinera/quiet_quality/issues/96) just now, if you'd like to take a crack at that first :-)
