### ISSUE TITLE
Allow the `command` to be overridden for certain tools

### ISSUE THREAD

**Issue by nevinera** [nevinera/quiet_quality#96]
This is mostly to enable further tools, but it could be useful for things like `rspec` as well. Right now, the runners define their own commands, but we could allow users to _customize_ those commands through the configuration file:

```
rspec:
  changed_files: true
  filter_messages: false
  base_command: "rspec --fail-false -f json"
  environment:
    SIMPLECOV: "false"
    INTEGRATION_TESTING: "false"
```

We'd need to update the commands to be handled as strings instead of arrays of arguments, which means passing them through bash.. probably not a big deal. We'd also need to handle the supplying of additional environment variables via the usual spawn interface, which I think `capture3` supports.
